Fixed most build errors by adding a default value to XML data for relationship_type.retired field.  Four build errors remain and are caused by a java.lang.NoClassDefFoundError when downloading the update.rdf from the module repository and a data issue with ConceptServiceTest-initialConcepts.xml.
 * Unable to fetch module update url: https://dev.openmrs.org/modules/download/formentry/update.rdf
 * No row with the given identifier exists: [org.openmrs.ConceptDatatype#0]

git-svn-id: http://svn.openmrs.org/openmrs/trunk@11679 5bac5841-c719-aa4e-b3fe-cce5062f897a